name: build
run-name: ${{github.actor}} build
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_PATH: ${{github.workspace}}
      BUILD_PATH: ${{github.workspace}}/../build
      BUILD_TYPE: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: CMake version
        run: cmake --version
      - name: Create build directory
        run: mkdir $BUILD_PATH
      - name: CMake configure ${{env.BUILD_TYPE}}
        run: cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$SOURCE_PATH/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -S $SOURCE_PATH -B $BUILD_PATH
      - name: CMake build ${{env.BUILD_TYPE}}
        run: cmake --build $BUILD_PATH --config $BUILD_TYPE
      - name: CTest ${{env.BUILD_TYPE}}
        run: ctest --test-dir $BUILD_PATH -C $BUILD_TYPE --output-on-failure -E NNTPConnectedTest.*
