name: build
run-name: ${{github.actor}} ${{github.event_name}}
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      SOURCE_PATH: ${{github.workspace}}
      BUILD_PATH: ${{github.workspace}}/../build
      BUILD_TYPE: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: CMake version
        run: cmake --version
      - name: CMake configure ${{env.BUILD_TYPE}}
        run: cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$SOURCE_PATH/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -S $SOURCE_PATH -B $BUILD_PATH
      - name: CMake build ${{env.BUILD_TYPE}}
        run: cmake --build $BUILD_PATH --config $BUILD_TYPE
      - name: CTest ${{env.BUILD_TYPE}}
        run: ctest --test-dir $BUILD_PATH -C $BUILD_TYPE --output-on-failure -E NNTPConnectedTest.*

  build-windows:
    runs-on: windows-latest
    env:
      SOURCE_PATH: ${{github.workspace}}
      BUILD_PATH: ${{github.workspace}}/../build
      BISON_ZIP_PATH: ${{github.workspace}}/../bison-2.4.1.zip
      BISON_PATH: ${{github.workspace}}/../bison
      BUILD_TYPE: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download bison
        shell: powershell
        run: |
          Invoke-WebRequest -Uri http://user.xmission.com/~legalize/trn-actions/bison-2.4.1.zip -OutFile "${{env.BISON_ZIP_PATH}}"
          mkdir ${{env.BISON_PATH}}
          cd ${{env.BISON_PATH}}
          7z x -y ${{env.BISON_ZIP_PATH}}
          Add-Content $env:GITHUB_PATH "${{env.BISON_PATH}}/bin"
      - name: CMake version
        run: cmake --version
      - name: CMake configure ${{env.BUILD_TYPE}}
        run: cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${{env.SOURCE_PATH}}/vcpkg/scripts/buildsystems/vcpkg.cmake -S ${{env.SOURCE_PATH}} -B ${{env.BUILD_PATH}}
      - name: CMake build ${{env.BUILD_TYPE}}
        run: cmake --build ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}}
      - name: CTest ${{env.BUILD_TYPE}}
        run: ctest --test-dir ${{env.BUILD_PATH}} -C ${{env.BUILD_TYPE}} --output-on-failure -E NNTPConnectedTest.*
