name: build
run-name: ${{github.actor}} build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: mkdir ${{github.workspace}}/../build
      - run: cmake --version
      - run: cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -S ${{github.workspace}} -B ${{github.workspace}}/../build
      - run: cmake --build ${{github.workspace}}/../build --config Release
      - run: ctest --test-dir ${{github.workspace}}/../build -C Release --output-on-failure
